site_name: Документация Selectyre
site_url: https://kkomissarov.github.io/selectyre-docs/
theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.expand
    - navigation.tracking
    - navigation.top
    - toc.follow
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Переключить на тёмную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Переключить на светлую тему
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png
  logo: assets/logo.png

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

nav:
  - Главная: index.md
  - Файлы выгрузки:
      - Ассортимент:
          - JSON: files/assortment/json.md
          - XML: files/assortment/xml.md
          - CSV шины: files/assortment/csv_tires.md
          - CSV диски: files/assortment/csv_wheels.md
      - Остатки и Цены:
          - JSON: files/availability/json.md
          - XML: files/availability/xml.md
          - CSV шины: files/availability/csv_tires.md
          - CSV диски: files/availability/csv_wheels.md
  - Настройка выгрузки в кабинете:
    - Старая версия: old_version.md
    - Новая версия: new_version.md
    - Профили наценок: settings/profiles.md
    - Файлы выгрузки: settings/export_files.md
