site_name: Документация Selectyre
site_url: https://docs.selectyre.ru
docs_dir: docs
site_dir: site
use_directory_urls: true

theme:
  name: material
  language: ru

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search

nav:
  - Главная: index.md
  - Настройка профилей наценок: settings/profiles.md
  - Настройка профилей ограничений: settings/restrictions.md
  - Файлы выгрузки:
      - Типы выгрузок: files/export_types.md
      - Настройка файлов выгрузки: settings/export_files.md
      - Структура данных: files/data_structure.md
      - Ассортимент:
          - JSON: files/assortment/json.md
          - XML: files/assortment/xml.md
          - CSV шины: files/assortment/csv_tires.md
          - CSV диски: files/assortment/csv_wheels.md
      - Остатки и Цены:
          - JSON: files/availability/json.md
          - XML: files/availability/xml.md
          - CSV шины: files/availability/csv_tires.md
          - CSV диски: files/availability/csv_wheels.md
